// data/steden.js
// ~500 Nederlandse steden en plaatsen voor programmatische SEO
// naam = weergavenaam, slug = URL-vriendelijke versie

const steden = [
  // G4
  { naam: 'Amsterdam', slug: 'amsterdam', provincie: 'Noord-Holland' },
  { naam: 'Rotterdam', slug: 'rotterdam', provincie: 'Zuid-Holland' },
  { naam: 'Den Haag', slug: 'den-haag', provincie: 'Zuid-Holland' },
  { naam: 'Utrecht', slug: 'utrecht', provincie: 'Utrecht' },
  // G5-G30
  { naam: 'Eindhoven', slug: 'eindhoven', provincie: 'Noord-Brabant' },
  { naam: 'Groningen', slug: 'groningen', provincie: 'Groningen' },
  { naam: 'Tilburg', slug: 'tilburg', provincie: 'Noord-Brabant' },
  { naam: 'Almere', slug: 'almere', provincie: 'Flevoland' },
  { naam: 'Breda', slug: 'breda', provincie: 'Noord-Brabant' },
  { naam: 'Nijmegen', slug: 'nijmegen', provincie: 'Gelderland' },
  { naam: 'Enschede', slug: 'enschede', provincie: 'Overijssel' },
  { naam: 'Haarlem', slug: 'haarlem', provincie: 'Noord-Holland' },
  { naam: 'Arnhem', slug: 'arnhem', provincie: 'Gelderland' },
  { naam: 'Zaanstad', slug: 'zaanstad', provincie: 'Noord-Holland' },
  { naam: 'Amersfoort', slug: 'amersfoort', provincie: 'Utrecht' },
  { naam: 'Apeldoorn', slug: 'apeldoorn', provincie: 'Gelderland' },
  { naam: 'Den Bosch', slug: 'den-bosch', provincie: 'Noord-Brabant' },
  { naam: 'Hoofddorp', slug: 'hoofddorp', provincie: 'Noord-Holland' },
  { naam: 'Zoetermeer', slug: 'zoetermeer', provincie: 'Zuid-Holland' },
  { naam: 'Zwolle', slug: 'zwolle', provincie: 'Overijssel' },
  { naam: 'Deventer', slug: 'deventer', provincie: 'Overijssel' },
  { naam: 'Leiden', slug: 'leiden', provincie: 'Zuid-Holland' },
  { naam: 'Dordrecht', slug: 'dordrecht', provincie: 'Zuid-Holland' },
  { naam: 'Delft', slug: 'delft', provincie: 'Zuid-Holland' },
  { naam: 'Alkmaar', slug: 'alkmaar', provincie: 'Noord-Holland' },
  { naam: 'Maastricht', slug: 'maastricht', provincie: 'Limburg' },
  { naam: 'Venlo', slug: 'venlo', provincie: 'Limburg' },
  { naam: 'Leeuwarden', slug: 'leeuwarden', provincie: 'Friesland' },
  { naam: 'Hilversum', slug: 'hilversum', provincie: 'Noord-Holland' },
  { naam: 'Helmond', slug: 'helmond', provincie: 'Noord-Brabant' },
  { naam: 'Westland', slug: 'westland', provincie: 'Zuid-Holland' },
  { naam: 'Ede', slug: 'ede', provincie: 'Gelderland' },
  { naam: 'Emmen', slug: 'emmen', provincie: 'Drenthe' },
  { naam: 'Sittard', slug: 'sittard', provincie: 'Limburg' },
  { naam: 'Oss', slug: 'oss', provincie: 'Noord-Brabant' },
  { naam: 'Hengelo', slug: 'hengelo', provincie: 'Overijssel' },
  { naam: 'Alphen aan den Rijn', slug: 'alphen-aan-den-rijn', provincie: 'Zuid-Holland' },
  { naam: 'Purmerend', slug: 'purmerend', provincie: 'Noord-Holland' },
  { naam: 'Roosendaal', slug: 'roosendaal', provincie: 'Noord-Brabant' },
  { naam: 'Spijkenisse', slug: 'spijkenisse', provincie: 'Zuid-Holland' },
  { naam: 'Hoorn', slug: 'hoorn', provincie: 'Noord-Holland' },
  { naam: 'Velsen', slug: 'velsen', provincie: 'Noord-Holland' },
  { naam: 'Schiedam', slug: 'schiedam', provincie: 'Zuid-Holland' },
  { naam: 'Leidschendam', slug: 'leidschendam', provincie: 'Zuid-Holland' },
  { naam: 'Capelle aan den IJssel', slug: 'capelle-aan-den-ijssel', provincie: 'Zuid-Holland' },
  { naam: 'Venray', slug: 'venray', provincie: 'Limburg' },
  { naam: 'Nieuwegein', slug: 'nieuwegein', provincie: 'Utrecht' },
  { naam: 'Gouda', slug: 'gouda', provincie: 'Zuid-Holland' },
  { naam: 'Zaandam', slug: 'zaandam', provincie: 'Noord-Holland' },
  { naam: 'Lelystad', slug: 'lelystad', provincie: 'Flevoland' },
  { naam: 'Katwijk', slug: 'katwijk', provincie: 'Zuid-Holland' },
  { naam: 'Roermond', slug: 'roermond', provincie: 'Limburg' },
  { naam: 'Vlaardingen', slug: 'vlaardingen', provincie: 'Zuid-Holland' },
  { naam: 'Assen', slug: 'assen', provincie: 'Drenthe' },
  { naam: 'Hardenberg', slug: 'hardenberg', provincie: 'Overijssel' },
  { naam: 'Bergen op Zoom', slug: 'bergen-op-zoom', provincie: 'Noord-Brabant' },
  { naam: 'Veenendaal', slug: 'veenendaal', provincie: 'Utrecht' },
  { naam: 'Zeist', slug: 'zeist', provincie: 'Utrecht' },
  { naam: 'Amstelveen', slug: 'amstelveen', provincie: 'Noord-Holland' },
  { naam: 'Barendrecht', slug: 'barendrecht', provincie: 'Zuid-Holland' },
  { naam: 'Huizen', slug: 'huizen', provincie: 'Noord-Holland' },
  { naam: 'Heerhugowaard', slug: 'heerhugowaard', provincie: 'Noord-Holland' },
  { naam: 'Terneuzen', slug: 'terneuzen', provincie: 'Zeeland' },
  { naam: 'Oldenzaal', slug: 'oldenzaal', provincie: 'Overijssel' },
  { naam: 'Woerden', slug: 'woerden', provincie: 'Utrecht' },
  { naam: 'Rijswijk', slug: 'rijswijk', provincie: 'Zuid-Holland' },
  { naam: 'Harderwijk', slug: 'harderwijk', provincie: 'Gelderland' },
  { naam: 'Middelburg', slug: 'middelburg', provincie: 'Zeeland' },
  { naam: 'Vlissingen', slug: 'vlissingen', provincie: 'Zeeland' },
  { naam: 'Leek', slug: 'leek', provincie: 'Groningen' },
  { naam: 'Doetinchem', slug: 'doetinchem', provincie: 'Gelderland' },
  { naam: 'Waalwijk', slug: 'waalwijk', provincie: 'Noord-Brabant' },
  { naam: 'Tiel', slug: 'tiel', provincie: 'Gelderland' },
  { naam: 'Weert', slug: 'weert', provincie: 'Limburg' },
  { naam: 'Zutphen', slug: 'zutphen', provincie: 'Gelderland' },
  { naam: 'Sliedrecht', slug: 'sliedrecht', provincie: 'Zuid-Holland' },
  { naam: 'Meppel', slug: 'meppel', provincie: 'Drenthe' },
  { naam: 'Hoogeveen', slug: 'hoogeveen', provincie: 'Drenthe' },
  { naam: 'Sneek', slug: 'sneek', provincie: 'Friesland' },
  { naam: 'Kerkrade', slug: 'kerkrade', provincie: 'Limburg' },
  { naam: 'Heerlen', slug: 'heerlen', provincie: 'Limburg' },
  { naam: 'Geleen', slug: 'geleen', provincie: 'Limburg' },
  { naam: 'Coevorden', slug: 'coevorden', provincie: 'Drenthe' },
  { naam: 'Boxtel', slug: 'boxtel', provincie: 'Noord-Brabant' },
  { naam: 'Veldhoven', slug: 'veldhoven', provincie: 'Noord-Brabant' },
  { naam: 'Meierijstad', slug: 'meierijstad', provincie: 'Noord-Brabant' },
  { naam: 'Waalre', slug: 'waalre', provincie: 'Noord-Brabant' },
  { naam: 'Driebergen', slug: 'driebergen', provincie: 'Utrecht' },
  { naam: 'Soest', slug: 'soest', provincie: 'Utrecht' },
  { naam: 'Baarn', slug: 'baarn', provincie: 'Utrecht' },
  { naam: 'Bussum', slug: 'bussum', provincie: 'Noord-Holland' },
  { naam: 'Naarden', slug: 'naarden', provincie: 'Noord-Holland' },
  { naam: 'Weesp', slug: 'weesp', provincie: 'Noord-Holland' },
  { naam: 'Diemen', slug: 'diemen', provincie: 'Noord-Holland' },
  { naam: 'Duivendrecht', slug: 'duivendrecht', provincie: 'Noord-Holland' },
  { naam: 'Uithoorn', slug: 'uithoorn', provincie: 'Noord-Holland' },
  { naam: 'Aalsmeer', slug: 'aalsmeer', provincie: 'Noord-Holland' },
  { naam: 'Haarlemmermeer', slug: 'haarlemmermeer', provincie: 'Noord-Holland' },
  { naam: 'Beverwijk', slug: 'beverwijk', provincie: 'Noord-Holland' },
  { naam: 'Heemskerk', slug: 'heemskerk', provincie: 'Noord-Holland' },
  { naam: 'Castricum', slug: 'castricum', provincie: 'Noord-Holland' },
  { naam: 'Langedijk', slug: 'langedijk', provincie: 'Noord-Holland' },
  { naam: 'Schagen', slug: 'schagen', provincie: 'Noord-Holland' },
  { naam: 'Enkhuizen', slug: 'enkhuizen', provincie: 'Noord-Holland' },
  { naam: 'Medemblik', slug: 'medemblik', provincie: 'Noord-Holland' },
  { naam: 'Stede Broec', slug: 'stede-broec', provincie: 'Noord-Holland' },
  { naam: 'Andijk', slug: 'andijk', provincie: 'Noord-Holland' },
  { naam: 'Drechterland', slug: 'drechterland', provincie: 'Noord-Holland' },
  { naam: 'Koggenland', slug: 'koggenland', provincie: 'Noord-Holland' },
  { naam: 'Opmeer', slug: 'opmeer', provincie: 'Noord-Holland' },
  { naam: 'Hollands Kroon', slug: 'hollands-kroon', provincie: 'Noord-Holland' },
  { naam: 'Den Helder', slug: 'den-helder', provincie: 'Noord-Holland' },
  { naam: 'Texel', slug: 'texel', provincie: 'Noord-Holland' },
  { naam: 'Wieringen', slug: 'wieringen', provincie: 'Noord-Holland' },
  { naam: 'Anna Paulowna', slug: 'anna-paulowna', provincie: 'Noord-Holland' },
  // Meer steden...
  { naam: 'Goirle', slug: 'goirle', provincie: 'Noord-Brabant' },
  { naam: 'Dongen', slug: 'dongen', provincie: 'Noord-Brabant' },
  { naam: 'Gilze', slug: 'gilze', provincie: 'Noord-Brabant' },
  { naam: 'Oosterhout', slug: 'oosterhout', provincie: 'Noord-Brabant' },
  { naam: 'Geertruidenberg', slug: 'geertruidenberg', provincie: 'Noord-Brabant' },
  { naam: 'Drimmelen', slug: 'drimmelen', provincie: 'Noord-Brabant' },
  { naam: 'Moerdijk', slug: 'moerdijk', provincie: 'Noord-Brabant' },
  { naam: 'Halderberge', slug: 'halderberge', provincie: 'Noord-Brabant' },
  { naam: 'Rucphen', slug: 'rucphen', provincie: 'Noord-Brabant' },
  { naam: 'Steenbergen', slug: 'steenbergen', provincie: 'Noord-Brabant' },
  { naam: 'Tholen', slug: 'tholen', provincie: 'Zeeland' },
  { naam: 'Goes', slug: 'goes', provincie: 'Zeeland' },
  { naam: 'Kapelle', slug: 'kapelle', provincie: 'Zeeland' },
  { naam: 'Borsele', slug: 'borsele', provincie: 'Zeeland' },
  { naam: 'Reimerswaal', slug: 'reimerswaal', provincie: 'Zeeland' },
  { naam: 'Hulst', slug: 'hulst', provincie: 'Zeeland' },
  { naam: 'Sluis', slug: 'sluis', provincie: 'Zeeland' },
  { naam: 'Veere', slug: 'veere', provincie: 'Zeeland' },
  { naam: 'Noord-Beveland', slug: 'noord-beveland', provincie: 'Zeeland' },
  { naam: 'Schouwen-Duiveland', slug: 'schouwen-duiveland', provincie: 'Zeeland' },
]

module.exports = { steden }
